########################### Default configuration ######################
baseURL = "https://guoxudong.io/"
title = "Guo Xudong's Blog"
homePageTitle = "郭旭东的博客 | 云原生之路"
# post pagination
paginate = "10"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # desable language from here
hasCJKLanguage = true
DefaultContentLanguage = "zh"
enableGitInfo = true

[outputs]
home = ["HTML", "RSS", "JSON", "Algolia"]

[outputFormats.Algolia]
  baseName = "algolia"
  isPlainText = true
  mediaType = "application/json"
  notAlternative = true

[params.algolia]
  appId = "QD329MV9NX"
  indexName = "guoxudong.io"
  searchOnlyKey = "172be5493ac0fc22f6af179cb9f02067"
  # vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
  # params = ["categories", "tags"]

############################### Plugins #################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/bigPicture/bigPicture.js"
[[params.plugins.js]]
link = "plugins/hex_md5/hex_md5.js"

########################### navigation ################################

[[menu.main]]
name = "Home"
URL = "/"
weight = 1

[[menu.main]]
name = "Blog"
URL = "post"
weight = 3

[[menu.main]]
name = "About"
URL = "about"
weight = 4


# # footer menu
# [[menu.footer]]
# name = "Policy"
# URL = "/policy"
# weight = 1

########################### Default parameters ######################
[params]
logo = "images/logo.png"
logo_footer = "images/logo.png"
# top header
top_header = false
footer_header = true
homePageTitle = "郭旭东的博客 | 云原生之路"
# Meta data
description = "云原生爱好者、实践者，专注于云原生及周边干货知识分享，实践达人，demo 小王子。"
author = " 郭旭东"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-173948186-1" # your id
# Baidu tongji
baidu_tongji_id = "4d507f28a1daf58fc7aca939db57093d"
# page sidebar quick contact form
quick_contact = false
# search
search = true
map = false
email = "guoxudong.dev@gmail.com"


# Gitalk
enableGitalk = true

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = false
link = "https://github.com/sunny0826"

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

[params.gitalk]
clientID = "4a9de8af7e1050d54872" # Your client ID
clientSecret = "3496974b10da2cbd315a427e45cd7f4a25ec2d05" # Your client secret
repo = "guoxudong.io" # The repo to store comments
owner = "sunny0826" # Your GitHub ID
admin= "sunny0826" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
id= "location.pathname" # The unique id of the page.
labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
perPage= 15 # Pagination size, with maximum 100.
pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

########################### social icon ############################
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/GuoXudong2"

[[params.social]]
icon = "fa-github"
link = "https://github.com/sunny0826"

[[params.social]]
icon = "fa-wechat"
# change the link after the public announcement
link = "https://mp.weixin.qq.com/s/6KFdeLBkUyyuPTRIhetiAw"

[[params.social]]
icon = "fa-envelope"
# change the link after the public announcement
link = "mailto:contact@guoxudong.dev@gmail.com"

[[params.social]]
icon = "fa-rss"
link = "https://guoxudong.io/post/index.xml"

################################### English language #####################################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 2
#home = "Home"
# footer content
footer_content = ""
# copyright
copyright = "Copyright &copy; 2018-{year} Guo Xudong"


################################### Chinese language #####################################
[Languages.zh]
languageName = "中文"
languageCode = "zh-cn"
contentDir = "content/zh"
weight = 1
#home = "主页"
# footer content
footer_content = "云原生爱好者、实践者，专注于云原生及周边干货知识分享，实践达人，demo 小王子。"
# copyright
copyright = "Copyright &copy; 2018-{year} Guo Xudong 保留所有权利"

########################### Chinese navigation ################################
# main menu
[[Languages.zh.menu.main]]
name = "主页"
weight = 1
URL = "/"

[[Languages.zh.menu.main]]
name = "博客"
weight = 2
URL = "post"

[[Languages.zh.menu.main]]
name = "关于"
weight = 3
URL = "about"

# footer menu
# [[Languages.zh.menu.footer]]
# name = "声明与政策"
# URL = "/policy"
# weight = 1

[frontmatter]
  date = ['date', 'publishDate', 'lastmod']
  lastmod = [':git', 'lastmod', 'date', 'publishDate']