name: Check Markdown links

on:
  schedule:
  # Run week at monday 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  - cron: "0 22 * * 2"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@master
      with:
        use-quiet-mode: 'yes'
        config-file: 'mlc_config.json'
